ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.PrintName = "Bandage"
ENT.Category = "Simple Medical"
ENT.Author = "Beb"
ENT.Contact = "Via steam"
ENT.Purpose = "Heals bleeding"
ENT.Instructions = "Use to heal bleeding"
ENT.Spawnable = true
ENT.AdminSpawnable = false