include("autorun/shared/sh_init.lua")
include("autorun/config/sm_config.lua")
include("autorun/config/sm_config.lua")

timer.Simple(startDiseaseDelay, function()
    net.Start("SMDiseaseCall")
        local ply = LocalPlayer()
        net.WriteEntity(ply)
    net.SendToServer()
end)
