ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.PrintName = "Splint"
ENT.Category = "Simple Medical"
ENT.Author = "Beb"
ENT.Contact = "Via steam"
ENT.Purpose = "Heals fracture"
ENT.Instructions = "Use to heal a fracture"
ENT.Spawnable = true
ENT.AdminSpawnable = false