ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.PrintName = "Rare Disease Cure"
ENT.Category = "Simple Medical"
ENT.Author = "Beb"
ENT.Contact = "Via steam"
ENT.Purpose = "Heals a rare disease"
ENT.Instructions = "Use to heal a rare disease"
ENT.Spawnable = true
ENT.AdminSpawnable = false