ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.PrintName = "Admin Medkit"
ENT.Category = "Simple Medical"
ENT.Author = "Beb"
ENT.Contact = "Via steam"
ENT.Purpose = "Heals everything!"
ENT.Instructions = "Use to heal everything!"
ENT.Spawnable = true
ENT.AdminSpawnable = true